from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import requests as _req


# Each WAF entry: response header names, server substrings, body substrings (all lowercase for matching)
_FINGERPRINTS: dict[str, dict[str, list[str]]] = {
    "cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id", "cf-mitigated"],
        "server": ["cloudflare"],
        "body": ["attention required! | cloudflare", "__cf_chl_", "ray id:"],
    },
    "akamai": {
        "headers": [
            "x-check-cacheable",
            "x-akamai-transformed",
            "akamai-origin-hop",
            "x-akamai-request-id",
            "x-akamai-session-info",
        ],
        "server": ["akamaighost", "akamai"],
        "body": ["akamaighost", "reference #"],
    },
    "imperva": {
        "headers": ["x-iinfo", "x-sigsci-tags", "x-sigsci-requestid", "incap-ses"],
        "server": ["incapsula"],
        "body": ["incapsula incident id", "_incap_ses_", "visid_incap_", "request unsuccessful"],
    },
    "aws": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amzn-trace-id", "x-amz-apigw-id"],
        "server": [],
        "body": [],
    },
    "f5": {
        "headers": ["x-waf-status", "x-wa-info", "x-cnection"],
        "server": ["bigip", "big-ip"],
        "body": ["the requested url was rejected", "big-ip", "your support id is"],
    },
    "modsecurity": {
        "headers": ["x-mod-security-id", "x-modsecurity-id"],
        "server": ["mod_security", "modsecurity"],
        "body": ["mod_security", "modsecurity", "not acceptable!", "406 not acceptable"],
    },
    "fastly": {
        "headers": ["x-fastly-request-id", "fastly-restarts", "x-served-by"],
        "server": [],
        "body": [],
    },
    "sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "server": ["sucuri"],
        "body": ["access denied - sucuri website firewall", "sucuri"],
    },
    "barracuda": {
        "headers": ["barra_counter_session"],
        "server": ["barracuda"],
        "body": ["barracuda networks", "bwf-block"],
    },
    "wordfence": {
        "headers": [],
        "server": [],
        "body": ["generated by wordfence", "wordfence is blocking your access"],
    },
    "azure": {
        "headers": ["x-azure-ref", "x-fd-healthprobe"],
        "server": [],
        "body": [],
    },
}

SUPPORTED_WAFS: list[str] = sorted(_FINGERPRINTS.keys())


def detect_waf(response: "_req.Response") -> str | None:
    """
    Fingerprint the WAF protecting a target from its HTTP response.

    Returns a lowercase WAF name from SUPPORTED_WAFS, or None if undetected.
    """
    headers_lower = {k.lower(): v.lower() for k, v in response.headers.items()}
    server = headers_lower.get("server", "")
    body_snippet = (response.text or "")[:8192].lower()

    for waf_name, fingerprints in _FINGERPRINTS.items():
        if any(h in headers_lower for h in fingerprints["headers"]):
            return waf_name
        if any(p in server for p in fingerprints["server"] if p):
            return waf_name
        if any(p in body_snippet for p in fingerprints["body"] if p):
            return waf_name

    return None
